import { StyleSheet } from 'react-native';

export const colors = {
  background: '#0B0F1A',
  surface: 'rgba(255,255,255,0.08)',
  surfaceBorder: 'rgba(255,255,255,0.15)',
  primary: '#FF3CAC',
  secondary: '#2B86C5',
  tertiary: '#784BA0',
  text: '#FFFFFF',
  textSecondary: 'rgba(255,255,255,0.75)',
  textMuted: 'rgba(255,255,255,0.7)',
  button: 'rgba(255,255,255,0.06)',
  buttonBorder: 'rgba(255,255,255,0.12)',
  success: '#4CAF50',
  error: '#F44336',
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundLayerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
  },
  bgBlob: {
    position: 'absolute',
    width: 420,
    height: 420,
    borderRadius: 24,
    opacity: 0.5,
  },
  bgBlobPink: {
    backgroundColor: colors.primary,
    top: -80,
    left: -70,
    transform: [{ rotate: '-18deg' }],
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
  },
  bgBlobBlue: {
    backgroundColor: colors.secondary,
    top: 120,
    right: -120,
    transform: [{ rotate: '12deg' }],
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
  },
  bgBlobPurple: {
    backgroundColor: colors.tertiary,
    bottom: -140,
    left: -100,
    transform: [{ rotate: '24deg' }],
    shadowColor: colors.tertiary,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.25,
    shadowRadius: 28,
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.surfaceBorder,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.35,
    shadowRadius: 30,
    elevation: 16,
  },
  button: {
    backgroundColor: colors.button,
    borderColor: colors.buttonBorder,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  primaryButtonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  title: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  input: {
    backgroundColor: colors.button,
    borderColor: colors.buttonBorder,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 16,
  },
  label: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 8,
  },
});
